### ISSUE TITLE
Great idea

### ISSUE THREAD

**Issue by mbtools** [pokrakam/abapDevSysInit#1]
Is it for transferring config from one system to the other or for setting up a system from scratch?

I keep a list of tables with system- and user-specific setting. If it's easy enough, I shall contribute here 😃

**Comment by pokrakam** [comment]
Love the way that GitHub presents it as "Great idea #1", it may well be my first great idea :-) 

It's for the repetitive tasks after spinning up a new developer system (NPL / A4H). Even with regular backups there are still occasions where you want to or have to start from scratch. Backups too old, SAP bring out a new version, broke something without noticing a while ago. 
So I had a couple of hacky programs to do some of the stuff. The SSL certificate was a bugbear, and when I saw that I decided to clean up and put everything into a public repo.

It's one program, the idea being copy/paste and go. My thoughts are currently to have all the config & personalisation in an include, again to make it copy-paste-able. Everything is in two ABAP programs, one public the other private.

I haven't pushed the source yet as I haven't had a chance to test it on a real system and it's one of those things that's hard to unit test and can definitely break things too.

**Comment by mbtools** [comment]
An all-in-one program is good. Easy to handle esp. for a new system.

Instead of config inside of code, I was thinking more of serializing the config to (private) repo. In the target system, you could then deserialize it again. Kind of like abapGit does it for data (tabu), but that feature is not powerful enough and anyway out-of-scope for AG. 

If it breaks something, we just bring up a new A4H image 😉 Looking forward to it 👍

**Comment by pokrakam** [comment]
Hmm, interesting idea about private repo. If we can fetch abapGit then I guess we can fetch a repo. But for now it's simpler than that, it was originally a couple of hacky programs I'd written for myself. 
I've uploaded my current version.

**Comment by mbtools** [comment]
Looks good! Maybe add a copy of `zdevsysinit_params` with empty entries that can be used as a template (`zdevsysinit_template`)

**Comment by pokrakam** [comment]
Good idea, added example. 
Re. pulling config from a private repo, I think copy/paste is easier for now. You still need to tell it where to pull from, and we either need the full abapGit to do so, or else pull the file content from a URL, which may be confusing if a user isn't aware of the difference between a link to the file's GitHub page vs link to the raw file.

**Comment by AndreaBorgia-Abo** [comment]
couple of minor suggestions:

- adding the option to flag a repo as favourite
- optionally clearing the existing abapGit database before importing the user-specified repos
