### ISSUE TITLE
Params template syntax error

### ISSUE THREAD

**Issue by fabianlupa** [pokrakam/abapDevSysInit#9]
Seems like some constants were changed in 3525b4eb28e012c28633d992cf5c4bae8c8f5cda and the copy-paste template hasn't been adjusted yet.

![image](https://github.com/pokrakam/abapDevSysInit/assets/5270359/59988c12-e418-413f-a361-47b79ff43e99)

https://github.com/pokrakam/abapDevSysInit/blob/655d4139c0499764968ec41c624661a1227f6f82/src/zdevsysinit.prog.abap#L2143-L2156

https://github.com/pokrakam/abapDevSysInit/blob/655d4139c0499764968ec41c624661a1227f6f82/zdevsysinit_params.sample.abap#L33-L34

**Comment by pokrakam** [comment]
Ah yes I went stricter on clean code and missed the example. Thanks for pointing out, fixed.
